version: '3.8'

services:
  identityservice:
    image: identityservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5075:5075"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5075
      - ConnectionStrings__DefaultConnection="Server=sql1;Database=master;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;"
    depends_on:
      - sql1
    command: >
      sh -c "sleep 40 && dotnet ef database update && dotnet IdentityService.dll"

  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  mssql-data:
